### ISSUE TITLE
Give the `settings.dest` option a default

### ISSUE THREAD

**Issue by vbalcom** [sugarcoat/sugarcoat#34]
When a user does not provide a `settings.dest`, configure.js does not error out. We don't catch the error until render.js.

Discuss: In light of this bug, should we be giving a default to `settings.dest`? Since it is relative to `settings.cwd` which takes process.cwd() as default, `settings.dest` should be the same. @ryanfitzer mentions that we want to make sure we don't accidentally override a user's project work. 
Should dest have a default folder name?

**Comment by tisAliG** [comment]
After this has been discussed a bit, we came to the conclusion that there should be a default for `settings.dest`. 

Here is the structure that should be created when the user doesn't provide a `settings.dest`(default dest): 
```
sugarcoat
    index.html
    [user]-css
    [user]-js
    [user]-images
    sugarcoat-assets
        css
        js
        images
```

The structure above demonstrates if the user were to provide their own `template.assets` but not a `settings.dest`.

**Comment by tisAliG** [comment]
Per our conversations today, since we are removing the CLI there should no longer be a default `dest`. After, `v1.0.0`, we may decide to bring back the CLI and it would make sense to create a default for `dest`.

**Comment by vbalcom** [comment]
`settings.dest` will be required in your config

**Comment by tisAliG** [comment]
In issue #32, I added errors when `dest` isn't required.
