### ISSUE TITLE
Create warning and error messages in Configure.js

### ISSUE THREAD

**Issue by tisAliG** [sugarcoat/sugarcoat#39]
We should be compiling all of the errors in an object when the config is run through configure, and output all of them at once, rather than only catching the first error ending outputting it immediately. 

We should also be adding this object of errors (and possibly warnings) to the expanded config. 

Example: when a file isn't found that is explicitly called for in the sections object, sugarcoat quietly passes over it without a warning. We should be outputting a warning that the file wasn't found.

**Comment by vbalcom** [comment]
This should resolve #34

**Comment by tisAliG** [comment]
@ryanfitzer and I just had a discussion about this. We came to the decision that we should be allowing the user to deal with the errors in their reject function. And that we should be making our errors uniform across every file (parser, render, etc..). And the uniform for errors should be a new errors object (constructor) of the error which should be pushed onto the errors array. 
In index, we are going to create an empty errors array and add it to the config. In configure, we are going to just simply push each error onto the errors array. Then in index, if any errors are present we will call promise.reject and hand back the errors array to the user. (we will have the entire config at this point including the errors array, but the user won't need the rest of the config file if their promise was rejected.) At that point the user's reject function will be called and they will get the errors array and do with it whatever they need.

We will also need to make sure that whenever any other promise that is called in our chain in index, that within that file we are adding to the errors array and if need be rejecting that promise in the file and returning the entire config with the errors array.

**Comment by tisAliG** [comment]
So far for errors in configure, I only have ones set up for required options. Meaning if an option that is required is not provided we make sure that we are getting an error. 

Are there any other errors that we should be creating within configure? @vbalcom @ryanfitzer

**Comment by tisAliG** [comment]
Issue #42 could be added to this. Should it be?

**Comment by tisAliG** [comment]
Since there are no responses. I'm going to send this into PR. And work on #42 in a new branch.

**Comment by tisAliG** [comment]
Closing as branch #50 has been merged into master.
