### ISSUE TITLE
Configure should error when `prefix.selector` is provided, but no `template` options are declared

### ISSUE THREAD

**Issue by vbalcom** [sugarcoat/sugarcoat#42]
This is to prevent users from adding an option that prevents Sugarcoat from scoping stylesheets correctly.

- [x] `prefix.selector` should error if no`prefix.assets` are provided
- [x] `prefix.selector` should error if no `template` options are provided

**Comment by tisAliG** [comment]
Closing as branch #51 has been merged into master.
