### ISSUE TITLE
Finalize Configuration Structure

### ISSUE THREAD

**Issue by ryanfitzer** [sugarcoat/sugarcoat#43]
There are currently 2 top-level properties:

```js
{
    settings: {},
    sections: {}
}
```

The `settings` property is really just a catchall for anything that doesn't make sense inside of `sections`. This was originally done in order to keep things organized, but it's starting to become confusing.

I propose the following structure:

```js
{
    dest: '',

    // Assets to copy into built pattern-library.
    copy: {/*SFF*/},

    // CSS and JavaScript to insert into default template.
    // All CSS rules are prefixed to prevent style bleed.
    include: {
      css: { /*SFF*/ },
      js: { /*SFF*/ }
    },

    display: {
        graphic: 'path/to/logo.png',
        title: 'text for <title> tag',
        headingText: 'text for page heading'
    },

    log: { /*npm/npmlog*/ },

    sections: [ /*section objects*/ ],

    template: { /*template customization*/ }
}
````

I have removed `cwd` (originally `settings.cwd`). We should just require that the `dest` path be relative to `process.cwd()`. All other path options in the config either implement the Standardized File Format or point to a specific file.

The structure for `template` is in a [separate issue](https://github.com/sugarcoat/sugarcoat/issues/44).

**Comment by vbalcom** [comment]
#58

**Comment by vbalcom** [comment]
Only item left for this implementation will be the log (#56)
