### ISSUE TITLE
Migrate to PostCSS

### ISSUE THREAD

**Issue by ryanfitzer** [sugarcoat/sugarcoat#46]
Let's get rid of Sass.

**Comment by tisAliG** [comment]
- [ convert sass styles to css styles ] 
- [ add postcss ]
- [ add postcss css variables plugin ]
- [ add postcss mixins plugin ]
- [ add postcss util plugin ]
- [ add css nano plugin ]
- [ add cssnext plugin ]
- [ add postcss import ]
- [ add postcss px to rem ]

**Comment by tisAliG** [comment]
@ryanfitzer @vbalcom Any other suggestions for postCSS plugins that we should incorporate?

**Comment by ryanfitzer** [comment]
I think a lot of those are already in `postcss-cssnext`. The only one I don't see in your list is `postcss-url`.

**Comment by tisAliG** [comment]
I had some issues using the latest version of postcss cssnext, after reading this: https://github.com/MoOx/postcss-cssnext/issues/357
I tried deleting the node modules folder and reinstalling everything and the error I was getting went away. I wanted to make note of this incase we have anymore issues going forward.
