### ISSUE TITLE
Postcss Bugs

### ISSUE THREAD

**Issue by vbalcom** [sugarcoat/sugarcoat#57]
- [x] Warning: postcss-cssnext found a duplicate plugin ('autoprefixer') in your postcss plugins. This might be inefficient. You should remove 'autoprefixer' from your postcss plugin list since it's already included by postcss-cssnext.
- [x] Media queries aren't working
- [x] Mixins.css should no longer be in an import statement
- [x] Add postcss plugin that removes comments

**Comment by tisAliG** [comment]
@vbalcom not sure what change did it, but the warning has gone away by fixing the two other issues. I also wanted to add an inline comment remover to postcss. Adding that to the issue.
